### ISSUE TITLE
PSA: NetTransport Rewrite 

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#1971]
If you develop server plugins and watch this repository, then this will almost definitely impact your plugins.

In general, the update should be backwards compatible. Nothing should have been removed, however several properties and methods have been marked obsolete.

You can opt-in to the NetTransport beta on Steam to try it out. There are several verbose logging options enabled to help you debug.

The dependency on `SteamNetworking` has been abstracted into "Net Transport Layers". The current default implementation uses `SteamNetworking`, but there is also an experimental Berkeley sockets TCP implementation that can be activated with the `-NetTransport=SystemSockets` command-line option. In the future the system sockets will be used for LAN servers, and when reliability is moved into a separate layer a UDP sockets implementation will be added. 

You can also try out an implementation of the new Steam networking with the `-NetTransport=SteamNetworkingSockets` command-line option.

Key changes and their impact:
- Connections are identified by an opaque `ITransportConnection` type. Players in the queue or online are still identified by SteamID however. Methods for sending to SteamIDs have been kept for backwards compatibility, but depend on the SteamID having an active connection.
- RPC channel is now a byte in the RPC header rather than per-message. This will impact anyone manually parsing send/receive RPC messages. If you are doing this then please comment and we will find a better workaround.
- Prior to the Connect message the connection SteamID is unknown. This will only impact plugins messing with the initial Workshop query message or initial Connect message.
- Channels are still of int type (32 bits), but are replicated as bytes (8 bits). They were only ever used to associate RPCs with a per-player component, and there are always less than 255 players on the server, so channel numbers are now recycled. In a future rewrite the channel numbers will be entirely replaced by a net addressable component id.
- Anyone using `SteamGameServerNetworking` to get the connection details should instead use `ITransportConnection.TryGetIPv4Address` and `ITransportConnection.TryGetPort`. Make sure to handle the false case because a future implementation of the "Steam Datagram Relay" will hide the remote address.

Please comment if you have any questions or concerns.

**Comment by PandahutMiku** [comment]
It would be nice if it logged what NetTransport you were using (SteamNetworking or SystemSockets) on server start.

**Comment by SDGNelson** [comment]
> It would be nice if it logged what NetTransport you were using (SteamNetworking or SystemSockets) on server start.

Will do!

> I tested around a bit and it seemed all fine, it certainly logs everything though.

Glad to hear that it is working fine for you so far. Was that with your plugins enabled as well?

> Any chance we could have a Net Transport option to use the new Steam Networking API?

That's the plan! It's the main motivation behind rewriting this. I am still working on that implementation, but it ought to be in the next beta version.

**Comment by PandahutMiku** [comment]
> Glad to hear that it is working fine for you so far. Was that with your plugins enabled as well?

Yes, however, we do not use Imperial or Avi, and nothing that patches/touches any of the packet events. Most we have is a few harmony patches specifically for our Roleplay Servers, but even then one of them are patching any provider or steamchannel events.

Glad to hear you plan on supporting the new Steam Networking API.

**Comment by warren39** [comment]
Is that "Steam Datagram Relay" will hide the server IP address, and avoid DDoS attack?

**Comment by SDGNelson** [comment]
Yes, Steam Datagram Relay (SDR) hides client and server addresses from each other. SDR is in beta though, and I am unsure whether it is available for non-official servers. Here is the documentation for it: https://partner.steamgames.com/doc/features/multiplayer/steamdatagramrelay

**Comment by SDGNelson** [comment]
Update: you can opt-in to the new Steam network with `-NetTransport=SteamNetworkingSockets`

The client now uses whichever implementation the server is using. Of the three implementations I think new Steam is the most robust, but for the next update it will default to old Steam in order to ensure bugs are with the game-level changes.

**Comment by PandahutMiku** [comment]
> Update: you can opt-in to the new Steam network with `-NetTransport=SteamNetworkingSockets`
> 
> The client now uses whichever implementation the server is using. Of the three implementations, I think the new Steam is the most robust, but for the next update, it will default to old Steam to ensure bugs are with the game-level changes.

Thanks!

I tried setting it up on a Test Server, but both I and another friend have the same error, trying to connect it just says "Lost Connection to host or Steam Network"

We have the exact same error in client.log:
```
[2020-09-11 22:31:05] Initializing ClientTransport_SteamNetworkingSockets
[2020-09-11 22:31:05] Client connecting to 51.83.58.37:27015
[2020-09-11 22:31:05] Client sent 1 byte PING_REQUEST message to server
[2020-09-11 22:31:05] Connection with invalid changed state from k_ESteamNetworkingConnectionState_None to k_ESteamNetworkingConnectionState_Connecting
[2020-09-11 22:31:06] Client sent 1 byte PING_REQUEST message to server
[2020-09-11 22:31:07] Client sent 1 byte PING_REQUEST message to server
[2020-09-11 22:31:08] Client sent 1 byte PING_REQUEST message to server
[2020-09-11 22:31:09] Client sent 1 byte PING_REQUEST message to server
[2020-09-11 22:31:10] Client sent 1 byte PING_REQUEST message to server
[2020-09-11 22:31:11] Client sent 1 byte PING_REQUEST message to server
[2020-09-11 22:31:12] Client sent 1 byte PING_REQUEST message to server
[2020-09-11 22:31:13] Client sent 1 byte PING_REQUEST message to server
[2020-09-11 22:31:14] Client sent 1 byte PING_REQUEST message to server
[2020-09-11 22:31:15] Connection with invalid changed state from k_ESteamNetworkingConnectionState_Connecting to k_ESteamNetworkingConnectionState_ProblemDetectedLocally
[2020-09-11 22:31:15] Client connection problem detected locally (5003) "Timed out attempting to connect"
[2020-09-11 22:31:15] Client transport failure: Lost connection to host or Steam network.
[2020-09-11 22:31:15] Returning to main menu
[2020-09-11 22:31:15] Disconnected
[2020-09-11 22:31:15] Connection with invalid changed state from k_ESteamNetworkingConnectionState_ProblemDetectedLocally to k_ESteamNetworkingConnectionState_None
[2020-09-11 22:31:16] Featured Workshop 2136497468 [7/16/2020 5:00:00 PM, 7/31/2020 5:00:00 PM]
[2020-09-11 22:31:16] Lost connection to host or Steam network.
```


The server has nothing of interest in its {Server_Name}.log
```
[2020-09-12 02:27:30] BattlEye Print: Initialized (v1.217)
[2020-09-12 02:27:30] Using login token
[2020-09-12 02:27:30] Parsed '-NetTransport' as 'SteamNetworkingSockets' from command-line
[2020-09-12 02:27:30] Initializing ServerTransport_SteamNetworkingSockets
[2020-09-12 02:27:30] Server listen socket bound to [::]:27015
[2020-09-12 02:27:30] Server created poll group 2147549184
[2020-09-12 02:27:30] Waiting for Steam servers...
[2020-09-12 02:27:42] 
[2020-09-12 02:27:43] Steam servers ready!
[2020-09-12 02:27:43] Workshop install folder: C:\Dedicated\PandahutServer19\steamapps\common\U3DS/Servers/Pandahut #19 [Super-Duper-Extra-Secret-TestServer]/Workshop/Steam
[2020-09-12 02:27:43] 0 workshop item(s) requested
[2020-09-12 02:27:43] Link spawns: 0 children, 812 sorted/normalized and 746 parents
[2020-09-12 02:27:43] Survival
[2020-09-12 02:27:43] NullReferenceException: Object reference not set to an instance of an object
[2020-09-12 02:27:44] Loading level: 8%
[2020-09-12 02:27:45] Loading level: 16%
[2020-09-12 02:27:45] Loading level: 25%
[2020-09-12 02:27:45] Loading level: 33%
[2020-09-12 02:27:45] Loading level: 41%
[2020-09-12 02:27:45] Loading level: 50%
[2020-09-12 02:27:45] Loading level: 58%
[2020-09-12 02:27:45] Loading level: 66%
[2020-09-12 02:27:45] Loading level: 75%
[2020-09-12 02:27:45] Loading level: 83%
[2020-09-12 02:27:45] Loading level: 91%
[2020-09-12 02:27:45] Loading level: 100%
[2020-09-12 02:27:45] Loading 16 landscape tiles
[2020-09-12 02:27:47] Static weather override: NONE
```

This happens with Rocketmod and on pure vanilla (no modules)



However, this ONLY happens when *not* using the default IP of the machine.

I tried inspecting via Wireshark but found nothing of interest. It just sends a bunch of data to the server's IP (51.83.58.37), ending with a packet saying it's timed out. It doesn't seem to be talking to the main/default IP (51.91.131.124) at all, but maybe Steam Servers are themselves.

If you want to debug it, I left the server up using the non-default IP on the lastest nettransport beta, running vanilla unturned (no rocketmod or any modules).

IP: 51.83.58.37 / test.pandahut.net
password 4fgighfdg
port 27015

I believe Steam Networking is reaching out to the default IP of the machine just like before trying to establish a connection, even though the Server's configured IP is not that.

Besides that, it seems smooth and I don't notice any glaring issues or problems. Running on the Default IP of the Machine works fine. All of our plugins are still fine and everything, we already treated the Session as it could be false/not return anything to begin with. It did seem faster to connect than usual, however, both of us noticed that our pings were anywhere from ~20-80ms higher than usual.  We are connecting to an EU Server but usually hover around ~120ms, not ~160ms and such. Does the new networking ping include processing time or something?

Thanks for taking the time to do this. Hopefully, the issue with the Default IP is something that can be fixed easily, just something more that needs to be set with the new Steam Networking API Perhaps?

**Comment by SDGNelson** [comment]
Thanks for giving it a try Miku! I really appreciate the details.

I wonder what the NullReferenceException in your server log is since it has no context (unusual). What map is the server running?

By "non default IP" do you mean that you are using the bind command to bind the listen socket to a specific address? If so, that is my bad, it looks like I did not hook that up yet. Will do. After that it should finally work properly as you pointed out in an issue quite a while ago!

**Comment by PandahutMiku** [comment]
> Thanks for giving it a try Miku! I really appreciate the details.
> 
> I wonder what the NullReferenceException in your server log is since it has no context (unusual). What map is the server running?

Running Washington. That error is gone now on Vanilla Only, and I think just related to Feasts (was on test server for a bit to see if it even still worked / needed changes), but it was trying to use old LevelLoaded Events, I cut the errors from Feast away but missed that most likely, my bad.
> By "non default IP" do you mean that you are using the bind command to bind the listen socket to a specific address? If so, that is my bad, it looks like I did not hook that up yet. Will do. After that it should finally work properly as you pointed out in an issue quite a while ago!

Yep, that's exactly what I mean. It looks like it half works already, shows server information via the IP it's bound to, but just doesn't let you connect. Let me know when you have that sorted out. Thanks!

**Comment by TH3AL3X** [comment]
Idk if it is this, but now i can't open 2 servers in the same instance....

**Comment by SDGNelson** [comment]
Binding a different address should work now. The transport layer will parse IPv4 and IPv6 addresses, however the session query and master server advertisement are still IPv4 until Steam hopefully updates them.

Everything has gone much smoother than expected and have not run into any bugs, so this might be released on Friday the 18th.

**Comment by PandahutMiku** [comment]
> Binding a different address should work now. The transport layer will parse IPv4 and IPv6 addresses, however the session query and master server advertisement are still IPv4 until Steam hopefully updates them.
> 
> Everything has gone much smoother than expected and have not run into any bugs, so this might be released on Friday the 18th.

Binding IP works perfectly fine now, and the main IP isn't being used at all.

I had two issues with randomly being disconnected (once, just randomly sitting around, got kicked out for being timed out) and another for "The Steam Servers aren't responding). Me, my laptop, and another admin of ours (Zero) tested for a long time after (~2 hours) and it hasn't happened at all again, so hopefully just freak occurence.

Otherwise, I'm not sure if you know of this or it doesn't matter, but my logs were being spammed by this

[2020-09-15 00:15:21] Internal: JobTempAlloc has allocations that are more than 4 frames old - this is not allowed and likely a leak
[2020-09-15 00:15:21] 
[2020-09-15 00:15:21] To Debug, enable the define: TLA_DEBUG_STACK_LEAK in ThreadsafeLinearAllocator.cpp. This will output the callstacks of the leaked allocations



I noticed this only happens when actively doing stuff like killing zombies and dying, and once it starts, it own't stop spamming like crazy. 

Also, when exiting servers, it spams this:

[2020-09-15 00:37:06] Internal: deleting an allocation that is older than its permitted lifetime of 4 frames (age = 15)

Here's my full log if needed (over Github's 10mb limit): https://cdn.pandahut.net/Client.log.txt


Besides that, is your plan still to release it optionally? Our plan was just to add it to one of our servers and monitor complaints and issues.

**Comment by SDGNelson** [comment]
Glad to hear it!

The rewrite can be thought of in two parts: abstracting the old Steam Networking behind the transport layer, and rewriting parts of the game code to use the transport layer rather than depending on Steam Networking. On Friday the game rewrite aspect will be released while defaulting to old Steam Networking, and then the next Friday the default transport layer will be changed to new Steam Networking.

Unturned does not use the job system, but those allocation errors have popped up from time to time, and judging from Unity bug threads there are some internal problems. I am also working on updating to Unity 2019 LS, so hopefully that will be fixed there.

**Comment by SDGNelson** [comment]
Today the builds are up on the preview branch and should be essentially good to go. Assuming no issues are reported between now and Friday I will release them first thing on Friday morning to provide plenty of time for patches.

**Comment by SDGNelson** [comment]
Playing on my test server and a few public servers it seems to be working smoothly so far. 🤞

**Comment by Johnanater** [comment]
I'm enabling it on some of my servers, let's see how this goes. 👍

**Comment by PandahutMiku** [comment]
It seems really solid. When it first came out, we added it to one of our servers which averaged around ~27 players for a few hours with zero issues.

However, one of our staff members has an issue joining any server using it as of right now.

[2020-09-19 23:13:54] Client connecting to 66.70.218.73:27015
[2020-09-19 23:13:54] Client connection problem detected locally (4003) "Bad cert: CA key 18220590129359924542 is not known to us"
[2020-09-19 23:13:54] Client transport failure: Unable to trust host encryption certificate.

Full Log:
[Client.log.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5251222/Client.log.txt)

I tried all of the common suggestions (check system time, verify unturned files, restart system, are you using 32-bit or 64-bit (64 bit)). A Quick Google search shows that this issue has effected other Valve games and such, but with no obvious solution. The player can join any server fine as long as it's not using the new networking. I'd appreciate any connection you might have.

**Comment by SDGNelson** [comment]
@PandahutMiku 

For the first issue I wonder if that player's firewall is blocking the request to the Steam server for cert details, but for the other ones I wonder if the certificates default lifespan is too short for a server running potentially days at a time. I will check into it and see if there are any options.

You are right about the voice log, will remove that!

**Comment by SDGNelson** [comment]
Considering these cert issues I will postpone making SteamNetworkingSockets the default until we sort them out. There should be an Unturned update this Friday with a variety of changes and fixes:

1. Will add a command-line option to disable the certificate requirement for testing.
2. Server will explicitly call `InitAuthentication`, retry on failure, and log changes in authentication availability.
3. Client will call `InitAuthentication` during startup to prepare, and show appropriate error messages if trying to connect without authentication available.

It looks like the cert expiry issue with long-running servers might be fixed in the Steam beta release based on this issue: https://github.com/ValveSoftware/GameNetworkingSockets/issues/129

**Comment by PandahutMiku** [comment]
> Considering these cert issues I will postpone making SteamNetworkingSockets the default until we sort them out. There should be an Unturned update this Friday with a variety of changes and fixes:
> 
> 1. Will add a command-line option to disable the certificate requirement for testing.
> 2. Server will explicitly call `InitAuthentication`, retry on failure, and log changes in authentication availability.
> 3. Client will call `InitAuthentication` during startup to prepare, and show appropriate error messages if trying to connect without authentication available.
> 
> It looks like the cert expiry issue with long-running servers might be fixed in the Steam beta release based on this issue: [ValveSoftware/GameNetworkingSockets#129](https://github.com/ValveSoftware/GameNetworkingSockets/issues/129)

The cert expiry issue is really odd.
We restart our servers everyday at 5 AM UTC.
Yesterday the server ran all day, no issue.
Today it ran around ~11 hours before the cert issue popped up again for everyone

[2020-09-22 16:40:28] Client connection problem detected locally (4003) "Bad cert: Cert expired 1227 seconds ago"
[2020-09-22 16:40:28] Client transport failure: Unable to trust host encryption certificate.

Does Steam cache them or something?
We stopped using the new networking for now regardless, odd issue though.

**Comment by SDGNelson** [comment]
The update today should make cert/auth related errors clearer. Unfortunately switching the default to Steam Networking Sockets will have to wait until the fix is propagated from Steam client beta to the public release.

**Comment by TH3AL3X** [comment]
For some reasons my server is sometimes not responding, I am receiving user complaints...
![image](https://user-images.githubusercontent.com/13141042/94339837-42c16200-fffd-11ea-9a7d-9cca30b20aa7.png)

**Comment by TH3AL3X** [comment]
[log.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5287133/log.txt)

**Comment by TH3AL3X** [comment]
I changed this parameter from Config.json and now is working fine, "Max_Packets_Per_Second": 100.0,

**Comment by SDGNelson** [comment]
@TH3AL3X With defaults, or with Steam Networking Sockets enabled? `Max_Packets_Per_Second` is unused in the base game now so increasing it would have been placebo.

**Comment by TH3AL3X** [comment]
> @TH3AL3X With defaults, or with Steam Networking Sockets enabled? `Max_Packets_Per_Second` is unused in the base game now so increasing it would have been placebo.

It was with default settings, but i think was a problem of my VPS server, anyways at this moment is working fine the server in the same instance, but only works when i start it at the same time, i mean if i close one server and i start it again, it will crash the other server, idk why...

**Comment by SDGNelson** [comment]
The certificate expiry fix was included in the Steam Client update today: https://store.steampowered.com/news/76246/

Everything should be working nicely with Steam Networking Sockets now. It might be time to enable them by default in this week's update!

**Comment by SDGNelson** [comment]
@TH3AL3X 

Regarding the SDR log: is the server running at less than 20 fps? That would be taking more than 50ms per frame explaining the lock warning.

> Also, I can't get the IP of users now, everytime return to 0.0.0.0, maybe i need to update RocketMod

Which method are you using? Note that the built-in GetIPv4Address methods returns false if the IPv4 address could not be determined, e.g. if using IPv6.

**Comment by TH3AL3X** [comment]
> @TH3AL3X
> 
> Regarding the SDR log: is the server running at less than 20 fps? That would be taking more than 50ms per frame explaining the lock warning.
> 
> > Also, I can't get the IP of users now, everytime return to 0.0.0.0, maybe i need to update RocketMod
> 
> Which method are you using? Note that the built-in GetIPv4Address methods returns false if the IPv4 address could not be determined, e.g. if using IPv6.

UnturnedPlayer player
player.IP

**Comment by TH3AL3X** [comment]
> @TH3AL3X
> 
> Regarding the SDR log: is the server running at less than 20 fps? That would be taking more than 50ms per frame explaining the lock warning.
> 
> > Also, I can't get the IP of users now, everytime return to 0.0.0.0, maybe i need to update RocketMod
> 
> Which method are you using? Note that the built-in GetIPv4Address methods returns false if the IPv4 address could not be determined, e.g. if using IPv6.

Idk, i will check that when i arrive to my home, but at this moment i put the old one

**Comment by PandahutMiku** [comment]
Seems the issue with expired certs still exists

[2020-10-12 02:54:30] Initializing ClientTransport_SteamNetworkingSockets
[2020-10-12 02:54:30] Client bypassing test for Steam Networking availability
[2020-10-12 02:54:30] Client connecting to 51.83.58.35:27015
[2020-10-12 02:54:30] Client connection problem detected locally (4003) "Bad cert: Cert expired 7120 seconds ago"
[2020-10-12 02:54:30] Client transport failure: Unable to trust host encryption certificate.

We had a bunch of users start complaining about this issue at the exact same time across. First thing I thought was our time sync was off, but it's fine. We just switched back to old networking for now.

**Comment by SDGNelson** [comment]
That's concerning... I will start a long-running dedicated server to try and replicate that in case there is any additional debug information in the Steam logs.

**Comment by PandahutMiku** [comment]
> That's concerning... I will start a long-running dedicated server to try and replicate that in case there is any additional debug information in the Steam logs.

Thanks for your reply,

I've verified this behavior happening on quite a few of our servers on entirely different machines.
In general what happens is:
Server switches to SteamNetworkingSockets, runs for 24 hours fine, restarts and a few hours later: Cert Expiring issue.

I have zero knowledge of SteamNetworkingsockets, but my best guess would be it's re-using the old cert.

In case it is of any use, I've sent the full logs (Server Current run with issue, previous run with no issue, my Client.log, and all of the other server logs.

Thanks for your time. 

If you need any other logs, or want us to help test anything, please don't hesitate to ask

**Comment by SDGNelson** [comment]
Thanks Miku! That's much appreciated. In the meantime for today's [3.20.12.2 Patch](https://steamcommunity.com/app/304930/discussions/0/2961639012580029589/) the default has been reverted to old Steam networking until the OpenSSL regression and cert expiry can be resolved.

**Comment by Trojaner** [comment]
![image](https://user-images.githubusercontent.com/1809172/96055293-589fa580-0e8c-11eb-99a1-8cdca19ecedc.png)
The issue seems to be fixed on Steam beta

**Comment by Fruten** [comment]
How now can I keep a player in the queue to change his nickname from the database?

**Comment by TH3AL3X** [comment]
> How now can I keep a player in the queue to change his nickname from the database?

uh???

**Comment by nanashi88** [comment]
![image](https://user-images.githubusercontent.com/59157332/97095177-eafe3100-1664-11eb-82ae-b2e342ffad3b.png)
so the issue was fixed on 19/10
but I haven't notice that last game update included moving again to the new NetTransport.

**Comment by SDGNelson** [comment]
It has not been made default again yet because there reportedly might still be an issue with certificate expiry. I have been running a couple long-running servers to see if it happens.

**Comment by Trojaner** [comment]
![image](https://user-images.githubusercontent.com/1809172/97647258-d8b83480-1a62-11eb-9421-9d7a98ec3a7f.png)
There was another update today related to this issue, but it was on the beta branch of Steam.

**Comment by joeymisfit** [comment]
@SDGNelson Are we still able to revert back to the old steamnetworking protocols if players are still receiving the Unable to trust host encryption certificate?

**Comment by SDGNelson** [comment]
@joeymisfit Can you share the Client.log from one of the players experiencing the trust issue? There is a relatively uncommon renewal issue that PandahutMiku reported to Valve, but otherwise it should be fairly stable. Ideally whatever the log says can be sorted out because this really needs to be the default going forward.

**Comment by RestoreMonarchy** [comment]
I'm hosting Unturned servers on Ubuntu 18.04 and since last update which made new Steam Networking default I'm getting this error message in console which lags the server. I'm sometimes getting this error even 30+ times in a row. It makes the server almost unplayable.
```
/data/src/steamnetworkingsockets/clientlib/steamnetworkingsockets_lowlevel.cpp (1149) : Assertion Failed: SDR service thread gave up on lock after waiting 59ms. This directly adds to delay of processing of network packets! 
```

I switched to legacy networking and I didn't notice this error or lags on it yet.

**Comment by SDGNelson** [comment]
@RestoreMonarchy it sounds like the server is running at less than 20 frames per second. There is not much we can do about that aside from improving performance

**Comment by joeymisfit** [comment]
@SDGNelson Attached are a few client.log's and client_prev.log's from the hosting company I work with.

[Client_Prev_-_Kopie.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5513775/Client_Prev_-_Kopie.log)
[Client_-_Kopie.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5513776/Client_-_Kopie.log)
[Client_Log.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5513777/Client_Log.txt)

**Comment by SDGNelson** [comment]
Thanks @joeymisfit! It looks like in all three cases it was the certificate expiry bug. PandahutMiku reported it to Valve this weekend on the GameNetworkingSockets repository. Hopefully we will hear from them soon, but for the meantime restarting the server should force the certificate renewal.

**Comment by joeymisfit** [comment]
Wonderful, thank you!

**Comment by Ehclipze** [comment]
I was wondering if you were able to tell me what is going on so that I can understand because I am not a coder and I'm just trying to play my main server. I get the Unable to trust host encryption certificate message.

**Comment by SDGNelson** [comment]
@Ehclipze sorry, the only workaround for the moment is for the server operator to restart the server.

**Comment by TH3AL3X** [comment]
> I'm hosting Unturned servers on Ubuntu 18.04 and since last update which made new Steam Networking default I'm getting this error message in console which lags the server. I'm sometimes getting this error even 30+ times in a row. It makes the server almost unplayable.
> 
> ```
> /data/src/steamnetworkingsockets/clientlib/steamnetworkingsockets_lowlevel.cpp (1149) : Assertion Failed: SDR service thread gave up on lock after waiting 59ms. This directly adds to delay of processing of network packets! 
> ```
> 
> I switched to legacy networking and I didn't notice this error or lags on it yet.

I have the same problem

**Comment by PandahutMiku** [comment]
> > I'm hosting Unturned servers on Ubuntu 18.04 and since last update which made new Steam Networking default I'm getting this error message in console which lags the server. I'm sometimes getting this error even 30+ times in a row. It makes the server almost unplayable.
> > 
> > ```
> > /data/src/steamnetworkingsockets/clientlib/steamnetworkingsockets_lowlevel.cpp (1149) : Assertion Failed: SDR service thread gave up on lock after waiting 59ms. This directly adds to delay of processing of network packets! 
> > ```
> > 
> > I switched to legacy networking and I didn't notice this error or lags on it yet.
> 
> I have the same problem

Some people in imperials discord were talking about it. Seems to be a specific plugin issue with something to do with a race condition. Maybe something to do with the main game thread being stalked by sql?

**Comment by TH3AL3X** [comment]
> > > I'm hosting Unturned servers on Ubuntu 18.04 and since last update which made new Steam Networking default I'm getting this error message in console which lags the server. I'm sometimes getting this error even 30+ times in a row. It makes the server almost unplayable.
> > > ```
> > > /data/src/steamnetworkingsockets/clientlib/steamnetworkingsockets_lowlevel.cpp (1149) : Assertion Failed: SDR service thread gave up on lock after waiting 59ms. This directly adds to delay of processing of network packets! 
> > > ```
> > > 
> > > 
> > > I switched to legacy networking and I didn't notice this error or lags on it yet.
> > 
> > 
> > I have the same problem
> 
> Some people in imperials discord were talking about it. Seems to be a specific plugin issue with something to do with a race condition. Maybe something to do with the main game thread being stalked by sql?

For some reasons the webclient, and plugins with sql also cause lag in linux...

**Comment by Trojaner** [comment]
> > > > I'm hosting Unturned servers on Ubuntu 18.04 and since last update which made new Steam Networking default I'm getting this error message in console which lags the server. I'm sometimes getting this error even 30+ times in a row. It makes the server almost unplayable.
> > > > ```
> > > > /data/src/steamnetworkingsockets/clientlib/steamnetworkingsockets_lowlevel.cpp (1149) : Assertion Failed: SDR service thread gave up on lock after waiting 59ms. This directly adds to delay of processing of network packets! 
> > > > ```
> > > > 
> > > > 
> > > > I switched to legacy networking and I didn't notice this error or lags on it yet.
> > > 
> > > 
> > > I have the same problem
> > 
> > 
> > Some people in imperials discord were talking about it. Seems to be a specific plugin issue with something to do with a race condition. Maybe something to do with the main game thread being stalked by sql?
> 
> For some reasons the webclient, and plugins with sql also cause lag in linux...

obviously it does because if you run these on main thread they will freeze the server for short times and hence cause lag / microlag...

**Comment by TH3AL3X** [comment]
> > > > > I'm hosting Unturned servers on Ubuntu 18.04 and since last update which made new Steam Networking default I'm getting this error message in console which lags the server. I'm sometimes getting this error even 30+ times in a row. It makes the server almost unplayable.
> > > > > ```
> > > > > /data/src/steamnetworkingsockets/clientlib/steamnetworkingsockets_lowlevel.cpp (1149) : Assertion Failed: SDR service thread gave up on lock after waiting 59ms. This directly adds to delay of processing of network packets! 
> > > > > ```
> > > > > 
> > > > > 
> > > > > I switched to legacy networking and I didn't notice this error or lags on it yet.
> > > > 
> > > > 
> > > > I have the same problem
> > > 
> > > 
> > > Some people in imperials discord were talking about it. Seems to be a specific plugin issue with something to do with a race condition. Maybe something to do with the main game thread being stalked by sql?
> > 
> > 
> > For some reasons the webclient, and plugins with sql also cause lag in linux...
> 
> obviously it does because if you run these on main thread they will freeze the server for short times and hence cause lag / microlag...

I'm using the thread method and async for prevent this, but i still get it :/, but only microlags...
