### ISSUE TITLE
Nobody can see the npcs from BowieD NPC maker after changing vendor IDs

### ISSUE THREAD

**Issue by ZapperPlayz** [SmartlyDressedGames/Unturned-3.x-Community#2294]
theres no errors in the error list about them except when the server loads up it gives this error

Object with no asset in region 36, 36: 4006 Medic_NPC 0b6529f3-4ac7-43f6-83aa-2784cb0e3eaf
Object with no asset in region 36, 36: 4005 Stylist_Shelby_NPC ffcfe607-1875-4c8a-a40e-9c31e8e6b16e
Object with no asset in region 37, 35: 4004 Farmer_Charles_NPC 8e060c17-b34a-4c51-b0c9-19f9c9417049
Object with no asset in region 37, 36: 4001 DrugLord_Buck_NPC 3e884e81-f26e-47b1-a543-e8106be2a06b
Object with no asset in region 37, 36: 4008 DrugLord_Leader_NPC e5857261-5816-4396-afc7-39602f58178b
Object with no asset in region 37, 36: 4002 SGT_Ricos_NPC 581e90cb-9e89-44d0-ad70-b50ee0bc73fd
Object with no asset in region 37, 36: 4007 Lieutenant_Charlie_NPC 5b0d3036-5511-4b0b-bc8e-433a4b7ba49d
Object with no asset in region 31, 32: 4009 DrugLord_Bert_NPC 551faf10-1b09-4a08-8fa2-8a10c344669c
Object with no asset in region 30, 32: 4003 Miner_Dave_NPC 546aa8b3-ea7a-4b5a-aa43-99262ad98723

**Comment by SDGNelson** [comment]
When you changed the ID did you change the name and GUID as well? Because only changing the conflicting IDs would have been necessary. If the ID, name, and GUID were changed then the game has no way to associate them with the ones in the level.

**Comment by ZapperPlayz** [comment]
I made the NPC vendor IDs different like you said and I went and made all the vendor ids 443* and the character IDs 441* and dialogues 442*

**Comment by ZapperPlayz** [comment]
I also managed to find another error in the error logs

**Comment by ZapperPlayz** [comment]
This is the error in error logs in unturned
(QuestAsset)Science_Guns[4017]:short ID is already taken by (DialogueAsset)Lieutenant_Charlie_Welcome[4017]
(QuestAsset)Scrap_Bar[4029]:short ID is already taken by(VendorAsset)DrugLordBert_Shop[4029]
(QuestAsset)Scrap_Cloth[4026]:short ID is already taken by(VendorAsset)Medic_NPC_Shop[4026
(QuestAsset)Scrap_Glue[4023]:short ID is already taken by(VendorAsset)MinerNicks_Shop[4023]
(QuestAsset)Scrap_Rope[4024]:short ID is already taken by(VendorAsset)Farmer_NPC_Shop[4024]
(QuestAsset)Scrap_Scrap[4025]:short ID is already taken by(VendorAsset)StylistShelby_NPC_Shop[4025]
(QuestAsset)Scrap_Sheet[4021]:short ID is already taken by(VendorAsset)DrugLordBuck_Shop[4021]
(QuestAsset)Scrap_Wire[4022]:short ID is already taken by(VendorAsset)SgtRicos_Shop[4022]

**Comment by ZapperPlayz** [comment]
How do I fix those 2 issues?

**Comment by iBowie** [comment]
Today I released 1.15.0, so instructions for this version:
1. Import Unturned assets
2. Open your project
3. Hit "Regenerate GUIDs" in characters tab
4. Right click ID box of every character, dialogue, vendor and quest you've made and click "Find unused ID"

It should fix IDs thing, yet you'll have to place npc on the map again

**Comment by ZapperPlayz** [comment]
Well I'm not using any quests as I dont understand them yet but what your telling me is I need to change GUIDs again and go to every characters dialogue and there a new button now for unused IDs? And then I go and I completely completely remove all the Old NPCs reset my unturned start it again Upload the NPCs and readd them after subscribing to the workshop file of the NPCs? If this is all %100 correct let me know so I know I'm not confusing myself and please dont close the ticket incase I need more help I'll close it when they are fully fixed cause I'm not the best at them at all

**Comment by ZapperPlayz** [comment]
So it asked me if I wanted to import unturned assets so I clicked yes and I clicked my NPCs file but then it told me to find the Unturned Directory so I went into steam apps and found it but idk if I done this wrong or if I am doing it right and confusing myself

**Comment by ZapperPlayz** [comment]
There still not there I changed the character IDs to 551* 552* 553* for the character dialogue and vendor IDs changed all the character GUIDs and I tried to find the unused IDs thing and I couldnt find it nobody can see them still

**Comment by ZapperPlayz** [comment]
I do like the update though and I did see that the update said something about it but i still couldnt find it

**Comment by ZapperPlayz** [comment]
There still not visible idk if I'm doing something wrong but even after I got rid of all the other NPC files I still am able to chose my old NPCs but I deleted them off the map and added the NPCs I made and named them in the editor 1-* so I'd be sure to pick the right one
