### ISSUE TITLE
Finding levels in file system should be rewritten

### ISSUE THREAD

**Issue by BeetMacol** [SmartlyDressedGames/Unturned-3.x-Community#3990]
# The problem

I have tried to join a server with the map BUAK that was installed on my computer. A message saying "This server is running a map you don't have." popped up. Redownloading the map didn't help as well as any solution suggested on the [official support page](https://support.smartlydressedgames.com/hc/en-us/articles/12230327880980--This-server-is-running-a-map-you-don-t-have-) (the map was selected anyways). The map actually didn't even work on Singleplayer (the game actually froze when I tried to load it).

# The cause

At some point I noticed that the name of the downloaded map is spelled using different casing than on the server (and probably in some map's metadata; not sure how that kind of stuff works in Unturned). In particular, the directory of the map on my computer is called `Buak` and the map is displayed on the server list as `BUAK`.

I assume that the lookup script ignores casing as on Windows two files cannot be named using the same name with different casing. On UNIX, however, two directories/maps could exit with the same names, but spelled using different casing. It seems like the function used to match the directory on Windows handled mismatching casing itself, while the Linux library does not.

# A workaround

As a workaround, a directory with the correct casing must be provided. I simply created a symlink to the right `Buak` directory that I called `BUAK` to help the lookup function find the right map and then I could finally join the server.

# The solution

Either the algorithm should accept directories of any casing, or the map folder names should be changed to match their actual names. Alternatively, the game could identify the maps using the directory names instead of the internal map names.

**Comment by SDGNelson** [comment]
The client and server both download the same workshop file, so the folder name *should* be `Buak` on the server as well. I wonder did you enter `Map BUAK` in the server's `Commands.dat` file? That would explain why it shows as `BUAK` in the server list.

**Comment by CyberAndrii** [comment]
There is a server with around 100 online players that I tried to join on Linux yesterday and got the same message. I think that's correct they have `Map BUAK` with all letters uppercase.

There is also a similar issue with mods that have non-matching .dat file and its containing folder names (for example, the folder name is all lowercase, but the .dat file name is not). I even made a script to rename those. This was before assets loading rewrite, but that's unlikely it was fixed.

**Comment by SDGNelson** [comment]
@CyberAndrii you're right that it's still a problem for capitalization mismatch between folder and asset name. Currently the reason is that it loads all `.asset` files as assets, but there are other `.dat` files which aren't assets like the translation files. One option to maybe improve this could be iterating the files in the folder and comparing the name case-insensitively.

**Comment by BeetMacol** [comment]
The high-capacity server mentioned here is the one I was trying to join. Well, in that case the map name provided to the client should be based on the actual map instead of the server's command.

**Comment by SDGNelson** [comment]
Fair point actually, thanks, I'll change that to fix the map name after the level is loaded.

**Comment by SDGNelson** [comment]
When I commented that I was thinking "just change the input map name to match the folder name, easy!" Except that the game doesn't know the actual capitalization unless it iterates the folders, and it doesn't currently keep a list of found maps. Won't be fixed in today's patch but is something I should rewrite.

**Comment by DanielWillett** [comment]
Whenever you get around to looking at this, a possibly related bug is that the editor glitches out a lot when you have the same map both in workshop content and in Maps. A lot of GL visuals float in the air or seem to be in the wrong place, reflections are in the wrong place sometimes, etc.
